CREATE DATABASE IF NOT EXISTS Sistema_de_Ventas;

CREATE USER IF NOT EXISTS 'seller'@'localhost';

ALTER USER 'seller'@'localhost' IDENTIFIED BY '';

GRANT ALL PRIVILEGES ON *.* TO 'seller'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;